[package]
name = "test_support"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
testdir = "0.9.3"
image = { workspace = true }
frei0r-rs2 = { workspace = true }
webvfx = { workspace = true }
