[package]
name = "webvfx"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyrender = "0.6.2"
anyrender_vello = "0.6.1"
blitz = "0.2.1"
parley = "0.6.0"  # Required to workaround https://github.com/DioxusLabs/blitz/issues/301
frei0r-rs2 = { git = "https://github.com/rectalogic/frei0r-rs.git", tag = "2.3.0" }
