[package]
name = "webvfx_filter"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "../build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
webvfx = { workspace = true }

[dev-dependencies]
test_support = { workspace = true }
