[package]
name = "webvfx_filter"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "../build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
webvfx = { path = "../webvfx" }
